// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddProject(arg1:string):Promise<model.ProjectInfo>;

export function ConfirmAll(arg1:string):Promise<void>;

export function DeepRescan(arg1:string):Promise<model.ChangeSet>;

export function GetChanges(arg1:string):Promise<model.ChangeSet>;

export function GetFileDiff(arg1:string,arg2:string):Promise<model.FileDiff>;

export function GetSettings():Promise<model.SettingsInfo>;

export function ListProjects():Promise<Array<model.ProjectInfo>>;

export function OpenFileLocation(arg1:string,arg2:string):Promise<void>;

export function RemoveProject(arg1:string):Promise<void>;

export function ResetDefaultPatterns():Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetCollapsedMode(arg1:boolean):Promise<void>;

export function SetCompactMode(arg1:boolean):Promise<void>;

export function SpawnStickyNote(arg1:string):Promise<void>;

export function StartAllMonitoring():Promise<void>;

export function StickyProjectID():Promise<string>;

export function UpdateDefaultPatterns(arg1:Array<string>):Promise<void>;

export function UpdateIgnore(arg1:string,arg2:Array<string>,arg3:boolean):Promise<void>;
