// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function ConfirmAll(arg1) {
  return window['go']['main']['App']['ConfirmAll'](arg1);
}

export function DeepRescan(arg1) {
  return window['go']['main']['App']['DeepRescan'](arg1);
}

export function GetChanges(arg1) {
  return window['go']['main']['App']['GetChanges'](arg1);
}

export function GetFileDiff(arg1, arg2) {
  return window['go']['main']['App']['GetFileDiff'](arg1, arg2);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function OpenFileLocation(arg1, arg2) {
  return window['go']['main']['App']['OpenFileLocation'](arg1, arg2);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetCollapsedMode(arg1) {
  return window['go']['main']['App']['SetCollapsedMode'](arg1);
}

export function SetCompactMode(arg1) {
  return window['go']['main']['App']['SetCompactMode'](arg1);
}

export function SpawnStickyNote(arg1) {
  return window['go']['main']['App']['SpawnStickyNote'](arg1);
}

export function StickyProjectID() {
  return window['go']['main']['App']['StickyProjectID']();
}

export function UpdateIgnore(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateIgnore'](arg1, arg2, arg3, arg4);
}
